Drop guzzle
sonata-project/SonataSeoBundle pull request #516
Opened 2021-03-04 14:02 UTC by wbloszyk

## Subject

I am targeting this branch, because this change provide BC-break.

2021-03-04 15:01 UTC, VincentLanglet commented on src/Block/Social/TwitterEmbedTweetBlockService.php
> +final class TwitterEmbedTweetBlockService extends BaseTwitterButtonBlockService implements EditableBlockService
We should `@final` first in the stable branch (for this class and others)

2021-03-04 15:22 UTC, wbloszyk commented on src/Block/Social/TwitterEmbedTweetBlockService.php
> +final class TwitterEmbedTweetBlockService extends BaseTwitterButtonBlockService implements EditableBlockService
#517

2021-03-05 14:19 UTC, phansys requested changes

2021-03-05 14:19 UTC, phansys commented on UPGRADE-3.0.md
> +If you using `sonata.seo.block.twitter.embed` service with guzzle, you must create custom service based on guzzle client and add it to configuration:
```suggestion
If you are using `sonata.seo.block.twitter.embed` service with Guzzle, you MUST create a custom service based on the Guzzle client and add it to configuration:
```

2021-03-05 14:19 UTC, phansys commented on UPGRADE-3.0.md
> +            client: `you_custom.guzzle_client` # Psr\Http\Client\ClientInterface
```suggestion
            client: `your_custom.guzzle_client` # Psr\Http\Client\ClientInterface
```

2021-03-05 14:19 UTC, phansys commented on UPGRADE-3.0.md
> +            message_factory: `you_custom.message_facory` # Psr\Http\Message\RequestFactoryInterface
```suggestion
            message_factory: `your_custom.message_facory` # Psr\Http\Message\RequestFactoryInterface
```

2021-03-05 14:19 UTC, phansys commented on src/Block/Social/TwitterEmbedTweetBlockService.php
>              // log error
This comment is a TODO?

2021-03-05 14:22 UTC, wbloszyk commented on src/Block/Social/TwitterEmbedTweetBlockService.php
>              // log error
It is no my comment. IMO it is TODO.

2021-03-05 14:35 UTC, phansys commented on src/Block/Social/TwitterEmbedTweetBlockService.php
>              // log error
I know, I just saw it during the review.
IMO, we should add a "TODO" or "@todo" prefix there.

2021-03-05 15:05 UTC, wbloszyk commented on src/Block/Social/TwitterEmbedTweetBlockService.php
>              // log error
This change is not in this PR scope.
I want resolve and prepare master to major release in nex week, so I will do it in other PR.

2021-03-05 15:17 UTC, phansys submitted a review, later dismissed

2021-03-06 13:49 UTC, VincentLanglet submitted a review, later dismissed

2021-03-06 23:55 UTC, core23 requested changes

2021-03-06 23:55 UTC, core23 commented on src/Block/Social/TwitterEmbedTweetBlockService.php
> +    public function getSupportedApiParams(): array
Why this change?

2021-03-06 23:55 UTC, core23 commented on src/Block/Social/TwitterEmbedTweetBlockService.php
> +    public function buildUri(bool $uriMatched, array $settings): string
Same here?

2021-03-07 01:46 UTC, wbloszyk commented on src/Block/Social/TwitterEmbedTweetBlockService.php
> +    public function buildUri(bool $uriMatched, array $settings): string
It is a getter with string return. Make it public will not change functionality but will add extra information require in tests.

2021-03-07 02:02 UTC, wbloszyk commented on src/Block/Social/TwitterEmbedTweetBlockService.php
> +    public function getSupportedApiParams(): array
This method always return the same array. Access to possible params for Twitter API should be public to allow validate it by own. Now unsupported params are ignored. 

BTW Mybe move it co constans will be better solution, becouse it depends on API, not object.

2021-03-07 12:43 UTC, VincentLanglet commented on src/Block/Social/TwitterEmbedTweetBlockService.php
> +    public function getSupportedApiParams(): array
A const is better.

2021-03-07 12:43 UTC, VincentLanglet commented on src/Block/Social/TwitterEmbedTweetBlockService.php
> +    public function buildUri(bool $uriMatched, array $settings): string
We should not add public just to help the tests.

It's better to not expose extra method than the interface ones.

2021-03-08 16:53 UTC, wbloszyk commented on src/Block/Social/TwitterEmbedTweetBlockService.php
> +    public function buildUri(bool $uriMatched, array $settings): string
I revert this change and final modifier. Lets make it in other PR.

2021-03-09 12:01 UTC, core23 approved these changes

2021-03-09 12:25 UTC, merged