Add finals messages
sonata-project/SonataSeoBundle pull request #517
Opened 2021-03-04 15:21 UTC by wbloszyk

## Subject

Add `@final` messages.

I am targeting this branch, because this change should be done in 2.x.

2021-03-05 10:02 UTC, VincentLanglet commented on tests/Block/Breadcrumb/BreadcrumbTest.php
>  class BreadcrumbMenuBlockService_Test extends BaseBreadcrumbMenuBlockService
You can already add final to all the tests. We do not provide BC on them.

2021-03-05 10:25 UTC, VincentLanglet submitted a review, later dismissed

2021-03-05 10:26 UTC, VincentLanglet commented
I think you need a new release with https://github.com/sonata-project/SonataBlockBundle/pull/840

2021-03-06 23:53 UTC, core23 approved these changes

2021-03-07 00:47 UTC, VincentLanglet commented
```
1x: The "Sonata\SeoBundle\Block\Social\TwitterEmbedTweetBlockService" class is considered final since sonata-project/seo-bundle 2.x. It may change without further notice as of its next major version. You should not extend it from "Sonata\SeoBundle\Tests\Fixtures\Block\TwitterEmbedTweetBSTest".
    1x in BreadcrumbTest::testBlockService from Sonata\SeoBundle\Tests\Block\Breadcrumb
```

2021-03-14 02:04 UTC, phansys requested changes
I think these changes are fine.
Just blocking the merge until the changelog and the upgrade notes are provided.

2021-03-14 07:57 UTC, wbloszyk commented
> I think these changes are fine.
> Just blocking the merge until the changelog and the upgrade notes are provided.

This PR will add only messages about final, so should we mark it as `patch`?

Yes for changelog.

Upgrade note is required? We do not provide BC-break so IMO it should be done in `Upgrade-4.0`.

2021-03-14 10:42 UTC, phansys commented
>Upgrade note is required? We do not provide BC-break so IMO it should be done in Upgrade-4.0.

From our [upgrade guide](https://github.com/sonata-project/SonataSeoBundle/blob/710022fa16105dabd7a2a264241a83d6b5f05d22/CONTRIBUTING.md#deprecation):
>Any deprecation MUST be documented in the corresponding UPGRADE-[0-9].x.md. The documentation MUST be filled inside the top unreleased section with a sub title.

2021-03-14 11:41 UTC, wbloszyk commented
> > Upgrade note is required? We do not provide BC-break so IMO it should be done in Upgrade-4.0.
> 
> From our [upgrade guide](https://github.com/sonata-project/SonataSeoBundle/blob/710022fa16105dabd7a2a264241a83d6b5f05d22/CONTRIBUTING.md#deprecation):
> 
> > Any deprecation MUST be documented in the corresponding UPGRADE-[0-9].x.md. The documentation MUST be filled inside the top unreleased section with a sub title.



> > Upgrade note is required? We do not provide BC-break so IMO it should be done in Upgrade-4.0.
> 
> From our [upgrade guide](https://github.com/sonata-project/SonataSeoBundle/blob/710022fa16105dabd7a2a264241a83d6b5f05d22/CONTRIBUTING.md#deprecation):
> 
> > Any deprecation MUST be documented in the corresponding UPGRADE-[0-9].x.md. The documentation MUST be filled inside the top unreleased section with a sub title.

Final is not equal to deprecation. Mark code will be in next major. People can use final class but cannot extends them. Mybe we should add notes about final and iternal in upgrade guide too?

IMO In this case I should add `BaseMediaBlockService` in 3.x to allow resolve problem with extending `MediaBlockServie` in this bundle and inheritances.

2021-03-15 03:24 UTC, phansys commented on tests/Fixtures/TwitterEmbedTweetBSTest.php
> + * @deprecated since sonata-project/seo-bundle 2.x, and will be remove in 3.0.
IMO, the test should not be deprecated, but marked with `@group legacy` annotation and a `NEXT_MAJOR` comment.

2021-03-15 17:08 UTC, phansys commented
>Final is not equal to deprecation. Mark code will be in next major. People can use final class but cannot extends them. Mybe we should add notes about final and iternal in upgrade guide too?

Adding a `@final` annotation to a class doesn't make it final, it just emits a deprecation message telling that it will be declared final in a future release, if the users are extending the class.
The method responsible for this behavior is [`DebugClassLoader::checkAnnotations()`](https://github.com/symfony/error-handler/blob/035e390eb7d8c8ad58ff1649f98ebac4e79f7878/DebugClassLoader.php#L433-L437).

2021-06-06 10:55 UTC, VincentLanglet commented
Do you have time to finish this PR @wbloszyk ?

2021-06-06 12:26 UTC, core23 approved these changes

2021-06-06 14:52 UTC, wbloszyk commented
@VincentLanglet I should find some time tomorrow, or at least in this week.

2021-06-12 15:23 UTC, VincentLanglet reviewed
Shouldn't some code of the last commit be in another PR ?

The PR is talking about Adding final/deprecation messages.
But the last commit is
- requiring nyholm/psr7
- adding some `@final` annotations
- deprecating some constant
- Adding a `tweetGetter` dependency to service
- Changing a || to &&
- ...

2021-06-12 22:15 UTC, core23 requested changes

2021-06-12 22:15 UTC, core23 commented on composer.json
> +        "nyholm/psr7": "^1.2",
Not related to this PR and not necessary at all

2021-06-14 12:25 UTC, wbloszyk commented
> Shouldn't some code of the last commit be in another PR ?
> 
> The PR is talking about Adding final/deprecation messages.
> But the last commit is
> 
> * requiring nyholm/psr7
> * adding some `@final` annotations
> * deprecating some constant
> * Adding a `tweetGetter` dependency to service
> * Changing a || to &&
> * ...

Agree, last commit should be add as seperated PR. I have some problem with this PR becouse:
- We haven't test for `tweet getter` part
- `\GuzzleHttp\Client()` is wrong configured (should be by `__construct()` argument, not by `setConfig()`,
- `tweet` setting help says: `Tweet id, URL or content. If you put the HTML content directly, other options won\'t be handled.` But `NULL` is returned when url/id pattern is not detected.

I change `||` to `&&` becouse it i move checking pattern to other place where chaning logic is required.

I didn't check it well but IMO bug was introduce in: https://github.com/sonata-project/SonataSeoBundle/commit/5e6ca8ff6942e1c4ff84c8072309514b5628f785

2021-09-04 22:50 UTC, SonataCI commented
Could you please rebase your PR and fix merge conflicts?

2021-09-14 07:42 UTC, closed without merging