Fix to issue #540
sonata-project/SonataSeoBundle pull request #541
Opened 2021-05-25 17:21 UTC by patrickmaynard

## Subject

Fix block bundle requirement

I am targeting this branch, because it is a clarification of an already-existing dependency, rather than a breaking change. (Currently, if a block bundle outside of the range I'm specifying is installed, the SEO bundle malfunctions. So this is a clarification, rather than something that significantly changes existing behavior.)

Closes ##540.

## Changelog

### Changed

-- Commit one: Add an acceptable version range for the block bundle to composer.json
-- Commit two: Fix missing comma in composer.json

2021-05-25 19:08 UTC, VincentLanglet commented on composer.json
> +        "sonata-project/block-bundle": ">=3.0 <4.0"
```suggestion
        "sonata-project/block-bundle": "^3.11"
```
And you can remove it from the conflict section then.

And also, the dependencies have to be alphabetically ordered

2021-05-25 19:19 UTC, core23 requested changes

2021-05-25 19:19 UTC, core23 commented on composer.json
>          "sonata-project/block-bundle": "<3.11",
You can remove this conflict and require-dev entry when adding this as a required dependency

2021-05-29 06:41 UTC, patrickmaynard commented
Thanks for the comments. Since there are a couple problems with pipelines running on this version, I'm closing this pull request and opening another. 

https://github.com/sonata-project/SonataSeoBundle/pull/542

I have integrated your comments on that request.

2021-05-29 06:41 UTC, closed without merging