Specify block bundle versions
sonata-project/SonataSeoBundle pull request #542
Opened 2021-05-29 06:39 UTC by patrickmaynard

Fix to issue #540

## Subject

Fix block bundle requirement

I am targeting this branch, because it is a clarification of an already-existing dependency, rather than a breaking change. (Currently, if a block bundle outside of the range I'm specifying is installed, the SEO bundle malfunctions. So this is a clarification, rather than something that significantly changes existing behavior.)

Closes #540.

## Changelog

Commit one: Changed composer.json. Removed conflict listing and dev dependency, since the block bundle is now listed as a main dependency.

2021-05-29 07:37 UTC, core23 requested changes

2021-05-29 07:37 UTC, core23 commented on composer.json
> +        "sonata-project/block-bundle": ">=3.11 <4.0",
```suggestion
        "sonata-project/block-bundle": "^3.11",
```

2021-05-29 13:15 UTC, core23 approved these changes

2021-05-31 16:48 UTC, patrickmaynard commented
@core23 it looks like we have a missing test case. From the failing pipeline:

```
PHP Fatal error:  Uncaught Error: Class 'Sonata\BlockBundle\Test\BlockServiceTestCase' not found in /home/runner/work/SonataSeoBundle/SonataSeoBundle/tests/Block/Breadcrumb/BreadcrumbTest.php
```

My guess is that we need to bump the block bundle version from ^3.11 to ^3.17 (which was the original dev dependency) in order to fix this. Does that sound like a good idea?

2021-05-31 19:30 UTC, VincentLanglet commented
I think it was introduce in 3.16
https://github.com/sonata-project/SonataBlockBundle/commit/63eb52533401c3fb9cd521b40922ac984ebfef2c.

But 3.17 is totally fine

2021-05-31 20:47 UTC, VincentLanglet approved these changes

2021-05-31 20:47 UTC, merged

2021-05-31 20:47 UTC, VincentLanglet commented
Thanks !