Add TweetGetter
sonata-project/SonataSeoBundle pull request #544
Opened 2021-06-14 12:30 UTC by wbloszyk

## Subject

I am targeting this branch, because this change respect BC.

Closes #{put_issue_number_here}.

## Changelog

```markdown
### Added
- Added `Sonata\SeoBundle\Twitter\TweetGetter` to work with tweet.
### Deprecated
- `TwitterEmbedTweetBlockService::TWITTER_OEMBED_URI`,
- `TwitterEmbedTweetBlockService::TWEET_URL_PATTERN`,
- `TwitterEmbedTweetBlockService::TWEET_ID_PATTERN`,
```

2021-06-14 13:33 UTC, core23 requested changes

2021-06-14 13:33 UTC, core23 commented on src/Twitter/TweetGetter.php
> +    public function loadTweet(array $settings): ?string
Can you add more specific type hints here?

2021-06-14 13:33 UTC, core23 commented on src/Twitter/TweetGetter.php
> +class TweetGetter
```suggestion
final class TweetGetter
```

2021-06-14 13:33 UTC, core23 commented on src/Twitter/TweetGetter.php
> +class TweetGetter
```suggestion
class TwitterClient
```

2021-06-16 18:22 UTC, VincentLanglet reviewed
Can we have some `NEXT_MAJOR` comment to explain every changes needed on master ?

2021-06-17 08:40 UTC, core23 commented on src/Twitter/TwitterClient.php
> +final class TwitterClient
Can you add an interface for this new client?

2021-06-21 12:22 UTC, phansys commented on src/Twitter/TwitterClient.php
> +                // log error
Is this a TODO comment?

2021-06-21 12:25 UTC, phansys commented on src/Twitter/TwitterClient.php
> +                'Make sure to add psr/http-client or guzzlehttp/guzzle to your composer.json.'
Why we are mentioning "psr/http-client" here if the check is made only against `\GuzzleHttp\Client`?

2021-06-21 12:53 UTC, phansys requested changes

2021-06-21 12:53 UTC, phansys commented on src/Twitter/TwitterClient.php
> +            'The direct Guzzle implementation is deprecated since 2.10 and will be removed with the next major release.',
```suggestion
            'The implementation based on guzzlehttp/guzzle is deprecated since sonata-project/seo-bundle 2.10 and will be removed in version 3.0.',
```

2021-06-21 12:53 UTC, phansys commented on src/Twitter/TwitterClient.php
> +        }
```suggestion       
        $parameters = array_filter($apiParams, static function ($value, $key): bool {
            return $value && \in_array($key, self::TWITTER_SUPPORTED_PARAMS, true);
        }, ARRAY_FILTER_USE_BOTH);
```

2021-06-21 12:53 UTC, phansys commented on src/Twitter/TwitterClient.php
> +            return sprintf('%s?%s', self::TWITTER_OEMBED_URI, implode('&', $parameters));
```suggestion
            return sprintf('%s?%s', self::TWITTER_OEMBED_URI, http_build_query($parameters));
```

2021-06-21 12:53 UTC, phansys commented on tests/Twitter/TwitterClientTest.php
> +        $tweet = $tweetGetter->loadTweet($settings);
Are these calls hitting the real Twitter API? IMO, we should not do that.

2021-09-04 22:50 UTC, SonataCI commented
Could you please rebase your PR and fix merge conflicts?

2021-09-11 10:24 UTC, core23 commented
The social media block were removed in #571.

IMHO there is no need for a TwitterClient anymore

2021-09-11 13:58 UTC, closed without merging