Increase phpstan level
sonata-project/SonataSeoBundle pull request #579
Opened 2021-09-14 11:41 UTC by core23

## Subject

Fix minor stan issues.

2021-09-14 11:44 UTC, VincentLanglet commented on phpstan.neon.dist
>  parameters:
```
includes:
    - phpstan-baseline.neon

parameters:
    level: 5
    bootstrapFiles:
        - vendor/bin/.phpunit/phpunit/vendor/autoload.php
    paths:
        - src
        - tests
    treatPhpDocTypesAsCertain: false
```

?

2021-09-14 11:47 UTC, VincentLanglet reviewed
You need the psalm-symfony plugin and the phpstan-symfony plugin IMHO

2021-09-16 07:03 UTC, core23 commented
Depends on #580 #585

2021-09-16 14:00 UTC, SonataCI commented
Could you please rebase your PR and fix merge conflicts?

2021-09-16 15:28 UTC, VincentLanglet commented on phpstan-baseline.neon
> +			message: "#^Parameter \\#1 \\$metas of method Sonata\\\\SeoBundle\\\\Seo\\\\SeoPage\\:\\:setMetas\\(\\) expects array\\<string, array\\<string, mixed\\>\\>, array\\<string, string\\> given\\.$#"
I would say we can fix this

2021-09-16 16:35 UTC, core23 commented on phpstan-baseline.neon
> +			message: "#^Parameter \\#1 \\$metas of method Sonata\\\\SeoBundle\\\\Seo\\\\SeoPage\\:\\:setMetas\\(\\) expects array\\<string, array\\<string, mixed\\>\\>, array\\<string, string\\> given\\.$#"
No idea how to fix this. This is a test issue where we ignore the type hints.

2021-09-16 17:44 UTC, VincentLanglet commented on phpstan-baseline.neon
> +			message: "#^Parameter \\#1 \\$metas of method Sonata\\\\SeoBundle\\\\Seo\\\\SeoPage\\:\\:setMetas\\(\\) expects array\\<string, array\\<string, mixed\\>\\>, array\\<string, string\\> given\\.$#"
I see, this is the call 
```
public function testInvalidMetas()
    {
        $this->expectException(\RuntimeException::class);

        $page = new SeoPage();
        $page->setMetas([
            'type' => 'not an array',
        ]);
    }
```

Indeed we cannot fix it, but on other project we ignored the error directly in the file with a psalm-suppress and phpstan-ignore https://github.com/sonata-project/SonataAdminBundle/blob/8a4e7f5210353c25b80614f2dec20bf4f7217ffe/tests/FieldDescription/TypeGuesserChainTest.php#L28

Kinda using the baseline as a TODO and this error will never be fixed.

2021-09-17 09:18 UTC, core23 commented
phpstan is failing in the ci, because the docker action is using an old version of the phpstan-symfony extension.

cc @OskarStark

2021-09-17 09:29 UTC, VincentLanglet commented
> phpstan is failing in the ci, because the docker action is using an old version of the phpstan-symfony extension.
> 
> cc @OskarStark

You should remove this ci build https://github.com/sonata-project/SonataSeoBundle/blob/3.x/.github/workflows/qa.yml
There is already https://github.com/sonata-project/SonataSeoBundle/blob/3.x/.github/workflows/qa.yaml

2021-09-17 09:58 UTC, core23 commented
> > phpstan is failing in the ci, because the docker action is using an old version of the phpstan-symfony extension.
> > cc @OskarStark
> 
> You should remove this ci build https://github.com/sonata-project/SonataSeoBundle/blob/3.x/.github/workflows/qa.yml
> There is already https://github.com/sonata-project/SonataSeoBundle/blob/3.x/.github/workflows/qa.yaml

Good catch! 👍

2021-09-17 10:22 UTC, VincentLanglet approved these changes, later dismissed

2021-09-17 12:51 UTC, jordisala1991 requested changes

2021-09-17 12:51 UTC, jordisala1991 commented on src/DependencyInjection/Compiler/ServiceCompilerPass.php
> +        $alias = $container->setAlias('sonata.seo.page', $config['default']);
no need this otv, you can directly call setPublic

2021-09-17 12:51 UTC, jordisala1991 commented on src/DependencyInjection/SonataSeoExtension.php
> +     * @param array<mixed> $config
mixed[]

2021-09-17 12:51 UTC, jordisala1991 commented on tests/DependencyInjection/ConfigurationTest.php
> +     * @return array<array-key, mixed>
mixed[], but I would recommend you to look at how it is done on AdminBundle and copy the same here

2021-09-17 12:51 UTC, jordisala1991 commented on tests/Seo/SeoPageTest.php
> +     * @psalm-suppress InvalidArgument
can we add a @see comment to explain why you have to supress?

2021-09-17 13:08 UTC, VincentLanglet commented on tests/Seo/SeoPageTest.php
> +     * @psalm-suppress InvalidArgument
Not really, this error is made on purpose to trigger the exception in the test.
We want to check that if we provide an invalid argument, an exception is thrown.

2021-09-17 15:12 UTC, VincentLanglet submitted a review, later dismissed

2021-09-17 15:17 UTC, jordisala1991 commented on src/DependencyInjection/SonataSeoExtension.php
> +     * @param array<mixed> $config
mixed[] (there are more uses like this).

2021-09-17 15:17 UTC, jordisala1991 commented on src/Seo/SeoPage.php
> +     * @param array<mixed>|string $meta
string|mixed[]

2021-09-17 19:44 UTC, franmomu approved these changes

2021-09-17 19:44 UTC, franmomu commented on src/DependencyInjection/Compiler/ServiceCompilerPass.php
> +        $container->setAlias('sonata.seo.page', $config['default'])->setPublic(true);
Not related to this PR, but do we need this alias to be public?

2021-09-17 22:21 UTC, jordisala1991 approved these changes

2021-09-18 06:04 UTC, VincentLanglet approved these changes

2021-09-18 06:16 UTC, merged