Allow setting global page prefix and suffix
sonata-project/SonataSeoBundle pull request #597
Opened 2021-09-25 18:25 UTC by core23

## Subject

I am targeting this branch, because this feature is BC.

Closes #157

## Changelog

```markdown
### Added
- Allow setting global page prefix and suffix 
```

2021-09-25 18:52 UTC, wbloszyk requested changes

2021-09-25 18:52 UTC, wbloszyk commented on docs/reference/installation.rst
> +            # title_suffix:  '| Some prefix'
```suggestion
            # title_suffix:  '| Sufix'
```

2021-09-25 18:53 UTC, wbloszyk commented on docs/reference/installation.rst
> +            # title_suffix:  '| Some prefix'
Examples for prefix and sufix should be simmilar.

2021-09-25 19:44 UTC, wbloszyk approved these changes

2021-09-26 09:58 UTC, VincentLanglet approved these changes

2021-09-26 09:59 UTC, merged

2021-09-26 09:59 UTC, VincentLanglet commented
Thanks