Merge 2.x into 3.x
sonata-project/SonataSeoBundle pull request #608
Opened 2021-10-06 18:30 UTC by core23

2021-10-06 18:47 UTC, franmomu submitted a review, later dismissed

2021-10-07 06:37 UTC, wbloszyk requested changes

2021-10-07 06:37 UTC, wbloszyk commented on src/Resources/config/blocks.php
> +            ]);
Can you set correct arguments here?

2021-10-07 06:37 UTC, wbloszyk commented on src/BreadcrumbInterface.php
> + * @deprecated since sonata-project/seo-bundle 2.x, to be removed in 3.0. Use Sonata\SeoBundle\Block\Breadcrumb\Breadcrumb instead.
IMO should be:
```suggestion
 * @deprecated since sonata-project/seo-bundle 2.x, to be removed in 3.0. Use Sonata\SeoBundle\Block\Breadcrumb\BreadcrumbBlockService instead.
```

2021-10-07 09:34 UTC, VincentLanglet commented on src/BreadcrumbInterface.php
> + * @deprecated since sonata-project/seo-bundle 2.x, to be removed in 3.0. Use Sonata\SeoBundle\Block\Breadcrumb\Breadcrumb instead.
This is just a merge, such a change should be done on 2.x branch to avoid conflict

2021-10-07 09:34 UTC, VincentLanglet commented on src/Resources/config/blocks.php
> +            ]);
What is wrong with the arguments ?

2021-10-07 09:50 UTC, wbloszyk commented on src/Resources/config/blocks.php
> +            ]);
Look at https://github.com/sonata-project/SonataSeoBundle/pull/608/files/f6d0606ac271a593e090363c5b5a5e45a9f76cd4#diff-953b23c1f0b95f9eb30962f3590b811ce55cb4a0191a2417a1f2f90adbae9c95

2021-10-07 19:15 UTC, VincentLanglet approved these changes

2021-10-07 20:02 UTC, wbloszyk approved these changes

2021-10-07 20:36 UTC, merged