Prepare major release
sonata-project/SonataSeoBundle pull request #609
Opened 2021-10-07 20:43 UTC by core23

## Subject

I am targeting this branch, because this should be the last changes for the next major release.

## Changelog

```markdown
### Changed
- Made `sonata.seo.sitemap.manager` service private

### Removed
- Remove all `sonata.seo.*.class` parameters from container
```

2021-10-07 20:48 UTC, VincentLanglet commented
If we follow the same strategy than other bundle, we should also 
- Bump phpstan level 8: https://github.com/sonata-project/SonataSeoBundle/blob/3.x/phpstan.neon.dist#L5
- Add the strict-rules plugin of phpstan (we found a lot of bug with it on SonataAdmin)
- Bump psalm level 3: https://github.com/sonata-project/SonataSeoBundle/blob/3.x/psalm.xml#L2

And we might determine what we do with https://github.com/sonata-project/SonataSeoBundle/pull/600#pullrequestreview-766353269

2021-10-07 21:10 UTC, core23 commented
> * Bump phpstan level 8: https://github.com/sonata-project/SonataSeoBundle/blob/3.x/phpstan.neon.dist#L5
> * Add the strict-rules plugin of phpstan (we found a lot of bug with it on SonataAdmin)
> * Bump psalm level 3: https://github.com/sonata-project/SonataSeoBundle/blob/3.x/psalm.xml#L2

Done

> And we might determine what we do with [#600 (review)](https://github.com/sonata-project/SonataSeoBundle/pull/600#pullrequestreview-766353269)

We can still implement the feature on the next major version

2021-10-07 21:56 UTC, franmomu commented on src/Resources/config/services.php
> +        ->set(SeoExtension::class)
We are using prefixed strings for the service names as suggested by Symfony: https://symfony.com/doc/current/bundles/best_practices.html#services

2021-10-07 21:56 UTC, franmomu commented on src/Resources/config/services.php
>              ->public()
I haven't checked the usages, but do we need services to be public?

2021-10-07 21:56 UTC, franmomu commented on src/Sitemap/SourceManager.php
> +        if (!isset($this->sources[$group]) || null === $this->sources[$group]) {
is the right branch needed? if `$this->sources[$group]` is null, `!isset($this->sources[$group])` would be `true` as well.

2021-10-08 05:55 UTC, core23 commented on src/Resources/config/services.php
> +        ->set(SeoExtension::class)
Reverted this. 

Looks like every symfony extension has a named service id: https://github.com/symfony/symfony/blob/ed712ef218a66d0bb1f659e62b4be1a47ab4c14a/src/Symfony/Bundle/TwigBundle/Resources/config/twig.php

2021-10-08 06:00 UTC, core23 commented on src/Resources/config/services.php
>              ->public()
Not sure if symfony still recommends using the service container. If it's deprecated we could make this private.

2021-10-08 06:20 UTC, franmomu commented on src/Resources/config/services.php
>              ->public()
[Looks like it depends on the usage](https://symfony.com/doc/5.2/bundles/best_practices.html#services):

> In addition, services not meant to be used by the application directly, should be defined as private. For public services, aliases should be created from the interface/class to the service id.

(I haven checked, but I guess they don't recommend using the service container directly.)

2021-10-08 06:31 UTC, franmomu approved these changes

2021-10-08 06:38 UTC, wbloszyk requested changes

2021-10-08 06:38 UTC, wbloszyk commented on src/Block/Breadcrumb/BreadcrumbBlockService.php
> +use Sonata\BlockBundle\Block\Service\BlockServiceInterface;
I dont see this interface.

2021-10-08 06:38 UTC, wbloszyk commented on src/DependencyInjection/SonataSeoExtension.php
> +            $connectionIterator = new Definition(DoctrineDBALConnectionSourceIterator::class, [
I'm not familiar with this, but if we have paramteter here should not be better to keep it and set it in config?

2021-10-08 06:38 UTC, wbloszyk commented on src/DependencyInjection/SonataSeoExtension.php
> +            $sitemapIterator = new Definition(SymfonySitemapSourceIterator::class, [
I'm not familiar with this, but if we have paramteter here should not be better to keep it and set it in config?

2021-10-08 06:40 UTC, wbloszyk commented
Before next major release we should decide about one importan thing.

After 2 months (59 days) support for PHP 7.3 will be end. If we drop it now then we can also declare types for parameters. Do it in stable branch will be BC. 

WDYT? @sonata-project/contributors

2021-10-08 06:41 UTC, wbloszyk commented on src/Block/Breadcrumb/BreadcrumbBlockService.php
> +use Sonata\BlockBundle\Block\Service\BlockServiceInterface;
My bad, not this bundle :)

2021-10-08 06:53 UTC, franmomu commented
> Before next major release we should decide about one importan thing.
> 
> After 2 months (59 days) support for PHP 7.3 will be end. If we drop it now then we can also declare types for parameters. Do it in stable branch will be BC.
> 
> WDYT? @sonata-project/contributors

It's already dropped in this bundle: https://github.com/sonata-project/SonataSeoBundle/blob/23cf25df16033c5197d2d0312118b175e9fdb9cf/composer.json#L23

2021-10-08 07:10 UTC, wbloszyk commented
I want check it this bundle before major release in the evening. So can we wait with major release to tomorrow?

2021-10-08 07:39 UTC, VincentLanglet approved these changes

2021-10-08 14:32 UTC, core23 commented on src/DependencyInjection/SonataSeoExtension.php
> +            $connectionIterator = new Definition(DoctrineDBALConnectionSourceIterator::class, [
We could improve this by allowing a custom service via the config, but for now we should get rid of all class parameters.

2021-10-08 14:36 UTC, wbloszyk approved these changes

2021-10-08 14:41 UTC, merged

2021-10-08 14:44 UTC, VincentLanglet commented
> I want check it this bundle before major release in the evening. So can we wait with major release to tomorrow?

We should try with an alpha/beta version anyway