Fix breadcrumb rendering
sonata-project/SonataSeoBundle pull request #619
Opened 2021-10-31 20:38 UTC by core23

## Subject

The `execute` method was missing, so the breadcrumb was rendered as an empty block.

This is basically a soft-port of https://github.com/sonata-project/SonataBlockBundle/blob/4.x/src/Block/Service/MenuBlockService.php.

I am targeting this branch, because this is a patch for the next stable release.

## Changelog

```markdown
### Fixed
- Fixed breadcrumb rendering
```

2021-10-31 20:51 UTC, phansys requested changes

2021-10-31 20:51 UTC, phansys commented on tests/Block/Breadcrumb/BreadcrumbTest.php
> +        $menu = $this->createMock(ItemInterface::class);
```suggestion
        $menu = $this->createStub(ItemInterface::class);
```

2021-10-31 20:51 UTC, phansys commented on tests/Block/Breadcrumb/BreadcrumbTest.php
> +            $this->createMock(Environment::class),
```suggestion
            $this->createStub(Environment::class),
```

2021-10-31 20:51 UTC, phansys commented on tests/Block/Breadcrumb/BreadcrumbTest.php
> +            $this->createMock(FactoryInterface::class)
```suggestion
            $this->createStub(FactoryInterface::class)
```

2021-10-31 20:51 UTC, phansys commented on tests/Block/Breadcrumb/BreadcrumbTest.php
> +            $this->createMock(Environment::class),
```suggestion
            $this->createStub(Environment::class),
```

2021-10-31 20:51 UTC, phansys commented on src/Block/Breadcrumb/BaseBreadcrumbMenuBlockService.php
> +            if (\array_key_exists($key, $mapping) && null !== $value) {
Minor performance improvement.
```suggestion
            if (null !== $value && \array_key_exists($key, $mapping)) {
```

2021-10-31 20:59 UTC, phansys submitted a review, later dismissed

2021-10-31 23:08 UTC, phansys approved these changes

2021-11-01 13:51 UTC, VincentLanglet approved these changes

2021-11-01 13:51 UTC, merged

2021-11-01 13:51 UTC, VincentLanglet commented
Thanks

2021-11-01 13:53 UTC, VincentLanglet commented
I just merged this, but didn't you want to target 3.x instead ? @core23

2021-11-01 14:24 UTC, core23 commented
> I just merged this, but didn't you want to target 3.x instead ? @core23

No, it's a bug on the next major branch.

2021-11-01 14:29 UTC, VincentLanglet commented
Since the 3.0 is still the alpha, the "next major branch" is the 3.x one, no ?
https://github.com/sonata-project/SonataSeoBundle/releases

2021-11-01 14:41 UTC, core23 commented
> Since the 3.0 is still the alpha, the "next major branch" is the 3.x one, no ? https://github.com/sonata-project/SonataSeoBundle/releases

Oh damn, you're right. 

We're still on the 2.x stable branch. Must have mixed this with the other projects where the stable one is 3.x.

2021-11-01 14:43 UTC, VincentLanglet commented
> > Since the 3.0 is still the alpha, the "next major branch" is the 3.x one, no ? https://github.com/sonata-project/SonataSeoBundle/releases
> 
> Oh damn, you're right.
> 
> We're still on the 2.x stable branch. Must have mixed this with the other projects where the stable one is 3.x.

A small drawback of the renaming of the branch, it's less easy to know the stable one.
I dunno, if we can do something about it to help us.

2021-11-01 15:42 UTC, jordisala1991 commented
> > > Since the 3.0 is still the alpha, the "next major branch" is the 3.x one, no ? https://github.com/sonata-project/SonataSeoBundle/releases
> 
> > 
> 
> > Oh damn, you're right.
> 
> > 
> 
> > We're still on the 2.x stable branch. Must have mixed this with the other projects where the stable one is 3.x.
> 
> 
> 
> A small drawback of the renaming of the branch, it's less easy to know the stable one.
> 
> I dunno, if we can do something about it to help us.

Equalize all Sonata versions could be useful, going mono repo could help too. Other other might need to rename again branches. Maybe a hint in the readme about the main branch. 🤷🏻‍♂️