Prepare 3.0.0 release
sonata-project/SonataSeoBundle pull request #637
Opened 2021-11-19 20:28 UTC by core23

🚀  It's time for the stable release 🚀

2021-11-19 21:07 UTC, OskarStark requested changes

2021-11-19 21:07 UTC, OskarStark commented on CHANGELOG.md
> +- [[#635](https://github.com/sonata-project/SonataSeoBundle/pull/635)] Fix block service registration ([@core23](https://github.com/core23))
Both habe the 635 🧐

2021-11-19 21:37 UTC, VincentLanglet approved these changes

2021-11-20 09:13 UTC, core23 commented on CHANGELOG.md
> +- [[#635](https://github.com/sonata-project/SonataSeoBundle/pull/635)] Fix block service registration ([@core23](https://github.com/core23))
Yes, because that PR fixes two different bugs.

2021-11-20 09:23 UTC, OskarStark approved these changes

2021-11-20 11:42 UTC, merged