Change menu label
sonata-project/SonataSeoBundle pull request #696
Opened 2022-10-06 08:28 UTC by eerison

## Subject

I am targeting this branch, because {reason}.

Closes #{put_issue_number_here}.

## Changelog

```markdown
### Added
- Added some `Class::newMethod()` to do great stuff.

### Changed

### Deprecated

### Removed

### Fixed

### Security
```

2022-10-06 08:41 UTC, eerison commented
@VincentLanglet Can I let the others translation missing it?
how do you usually handle new translations for all languages?

2022-10-06 08:46 UTC, VincentLanglet commented
> @VincentLanglet Can I let the others translation missing it? how do you usually handle new translations for all languages?

I generally try to add translation thanks to some knowledge, review or translator.

In french, `breadcrumb menu` is `Menu fil d'Ariane`

2022-10-06 09:05 UTC, eerison commented
> > @VincentLanglet Can I let the others translation missing it? how do you usually handle new translations for all languages?
> 
> I generally try to add translation thanks to some knowledge, review or translator.
> 
> In french, `breadcrumb menu` is `Menu fil d'Ariane`

Ok I asked some guys and They suggested translate `Menu` only, because `Breadcrumb` doesn't make sense!

2022-10-06 09:11 UTC, eerison commented
Just to have a different icon, what do you think about this one

https://fontawesome.com/v5/icons/angle-double-right?s=solid&f=classic

or should I keep the same (bars)?

2022-10-06 09:13 UTC, VincentLanglet commented
> Just to have a different icon, what do you think about this one
> 
> https://fontawesome.com/v5/icons/angle-double-right?s=solid&f=classic
> 
> or should I keep the same (bars)?

This icon might be a good idea indeed

2022-10-06 09:18 UTC, eerison commented
<img width="1404" alt="Screenshot 2022-10-06 at 11 17 30" src="https://user-images.githubusercontent.com/6358755/194275497-227aa282-877e-481b-a211-6a8ef05adf89.png">
Ok then it stays like this, I liked it 💅🏼

2022-10-06 09:20 UTC, VincentLanglet commented
We're changing from `fa` to `fas` are we sure font awesome 5 is used by all the seoBundle users ?
Or should we stay with something like `<i class="fa fa-angle-double-right"></i>` ?

2022-10-06 09:23 UTC, eerison commented
> We're changing from `fa` to `fas` are we sure font awesome 5 is used by all the seoBundle users ? Or should we stay with something like `<i class="fa fa-angle-double-right"></i>` ?

hmmm well I was following the sonata admin 4!

2022-10-06 09:25 UTC, eerison commented
> > We're changing from `fa` to `fas` are we sure font awesome 5 is used by all the seoBundle users ? Or should we stay with something like `<i class="fa fa-angle-double-right"></i>` ?
> 
> hmmm well I was following the sonata admin 4!

I tested and it works on both way `fa` or `fas`

2022-10-06 09:27 UTC, eerison commented
But as we require [block bundle 4](https://github.com/sonata-project/SonataSeoBundle/blob/3.x/composer.json#L25), I guess the user is more or less forced to use sonata 4, don't you?

2022-10-06 11:43 UTC, VincentLanglet commented
> But as we require [block bundle 4](https://github.com/sonata-project/SonataSeoBundle/blob/3.x/composer.json#L25), I guess the user is more or less forced to use sonata 4, don't you?

We dont force to use sonataAdmin 4. People might use just BlockBundle and SeoBubdle maybe...

I dunno where come from this icon, so I dunno if we can use font awesome 5 without a BC break...

2022-10-06 12:47 UTC, eerison commented
well Ok lets use `fa`

2022-10-06 12:49 UTC, VincentLanglet approved these changes

2022-10-06 12:50 UTC, VincentLanglet requested changes

2022-10-06 12:50 UTC, VincentLanglet commented on src/Resources/translations/SonataSeoBundle.de.xliff
> +        <target>Breadcrumb Menü</target>
Where did you find your translations ?
I would say it's weird Breadcrumb is said Breadcumb in De, It, Nl and Ru

2022-10-06 12:53 UTC, eerison commented on src/Resources/translations/SonataSeoBundle.de.xliff
> +        <target>Breadcrumb Menü</target>
I asked some german opinion internally, And was suggested translate just `Menu`

I got two option `Breadcrumb-Menü` or `Sekundäre Navigation`

2022-10-06 12:53 UTC, eerison commented on src/Resources/translations/SonataSeoBundle.de.xliff
> +        <target>Breadcrumb Menü</target>
and I took the first one

2022-10-06 12:54 UTC, VincentLanglet approved these changes

2022-10-11 07:29 UTC, eerison commented
@jordisala1991 could you review please 👀

2022-10-20 07:28 UTC, jordisala1991 approved these changes

2022-10-20 07:29 UTC, jordisala1991 commented
Thank you @eerison

2022-10-20 07:29 UTC, merged