bump symfony version to 7
sonata-project/SonataSeoBundle pull request #733
Opened 2023-12-05 15:00 UTC by abdellahrk

## Add support for Symfony 7

This merely adds supports for Symfony 7 which has just been released.

### 3.x
I am targeting this branch, because it adds support of a new Symfony version.

## Changelog

## [Unreleased]

## [3.x] - 2023-12-05

### Added 
 - Support for Symfony 7

2023-12-05 15:51 UTC, VincentLanglet requested changes

2023-12-05 15:51 UTC, VincentLanglet commented on composer.json
> +        "php": "^8.0|^8.2",
```suggestion
        "php": "^8.0",
```
Is ok, it means already 8.0, 8.1, 8.2, 8.3 etc

2023-12-05 15:51 UTC, VincentLanglet commented on composer.json
> +        "symfony/config": "^5.4|^6.2|^7.0",
Please keep the same format that before
```
"^5.4 || ^6.2 || ^7.0",
```

2023-12-05 16:33 UTC, abdellahrk commented on composer.json
> +        "php": "^8.0|^8.2",
Okay @VincentLanglet noted.

2023-12-05 16:38 UTC, abdellahrk commented on composer.json
> +        "symfony/config": "^5.4|^6.2|^7.0",
fixed @VincentLanglet

2023-12-05 16:42 UTC, VincentLanglet commented
The rector issue is unrelated, I'm on it

2023-12-05 16:42 UTC, VincentLanglet submitted a review, later dismissed

2023-12-05 16:43 UTC, VincentLanglet commented
Thanks, I'll merge this and release it when I have time. Unless @jordisala1991 do it

2023-12-19 10:06 UTC, VincentLanglet commented
Sorry, do you have time to rebase the branch ? @abdellahrk

2023-12-21 08:53 UTC, abdellahrk commented
Yes sure @VincentLanglet

2023-12-24 10:42 UTC, VincentLanglet approved these changes

2023-12-24 10:42 UTC, merged